### ISSUE TITLE
Compatibility with Avro v1.9.0

### ISSUE THREAD

**Issue by tjwp** [salsify/avromatic#113]
The avro_turf dependency for this gem is not yet compatible with avro 1.9.0: https://github.com/dasch/avro_turf/pull/94

Some WIP on this branch: https://github.com/salsify/avromatic/compare/tjwp-avro-1.9.0

**Comment by Merbs** [comment]
It looks like it is now compatible in v0.9.0 as of July 14 (22 days ago).

https://github.com/dasch/avro_turf/blob/master/CHANGELOG.md

Does that now make it possible to release a new compatible version of avromatic?

**Comment by tjwp** [comment]
I don't think a new release is needed for compatibility with avro 1.9.0 now that the dependencies have released versions that are compatible.

Let us know if you find any further conflicts!

**Comment by jturkel** [comment]
Closing this since Avromatic works with Avro 1.9. Please reopen this if you find an issue.
