### ISSUE TITLE
LoadError: cannot load such file -- avro_turf/messaging

### ISSUE THREAD

**Issue by travisofthenorth** [salsify/avromatic#15]
Because of some other gem dependencies, I am locked at version 0.5.0 of `avromatic` and `avro_turf`. From Gemfile.lock:
```
    avro (1.7.7)
      multi_json
    avro_turf (0.5.0)
      avro (~> 1.7.7)
    avromatic (0.5.0)
      activemodel
      activesupport
      avro (>= 1.7.7)
      avro_turf
      virtus
```

Version 0.5.0 of `avromatic` calls `require 'avro_turf/messaging'` in `avromatic.rb`, but that module doesn't actually exist in v0.5.0 of `avro_turf`.

**Comment by tjwp** [comment]
@travisofthenorth What are the other dependencies that are keeping you locked to `avro_turf` 0.5.0?

**Comment by travisofthenorth** [comment]
@tjwp I was using a higher version of `excon` (0.48.0). I actually managed to roll that back to allow 0.7.0 of the `avromatic` gems, but I thought it was worth mentioning that valid combinations of `avromatic` and `avro_turf`, for example, will break.

**Comment by tjwp** [comment]
Thanks for bringing it up. I'm going to look into whether that `excon` restriction can be more flexible.

**Comment by travisofthenorth** [comment]
@tjwp the constraint is in `avro_turf`. Here's a PR for that: https://github.com/dasch/avro_turf/pull/40

**Comment by travisofthenorth** [comment]
The above PR has been merged, so the `excon` dependency shouldn't be an issue.

**Comment by tjwp** [comment]
Great! Thanks for following up on it.
