### ISSUE TITLE
Possible to include module in anonymous nested model?

### ISSUE THREAD

**Issue by minionOfZuul** [salsify/avromatic#161]
I have a nested schema that looks much like the schema in spec/avro/schema/test/nested_nested_record.avsc - i.e. multiple levels of nested records. I would like to manually define a class for each of the generated nested models, instead of the anonymous generated classes, so that I can include some validation methods that are written in a separate module. Concretely,

```schema.avsc
{
  "type": "record",
  "name": "nested_nested_record",
  "namespace": "test",
  "fields": [
    {
      "name": "sub",
      "type": {
        "type": "record",
        "name": "__nested_nested_record_sub_record",
        "namespace": "test",
        "fields": [
          {
            "name": "subsub",
            "type": {
              "type": "record",
              "name": "__nested_nested_record_sub_subsub_record",
              "namespace": "test",
              "fields": [
                {
                  "name": "n",
                  "type": "null"
                }
              ]
            }
          }
        ]
      }
    }
  ]
}
```
I would like to write an Avromatic model for the `sub` and `subsub` records so I can include custom validations. It's unclear from the docs and the code how I would go about doing this. If I write a model for the top-level record like this:

```ruby
class NestedNestedRecord
  include Avromatic::Model.build(schema_name: 'test.nested_nested_record')
end
```

and then a model for the `sub` record like this:

```ruby
class SubRecord
  include Avromatic::Model.build(schema_name: 'test.__nested_nested_record_sub_record')  
  validates :foo, numericality: { greater_than_or_equal_to: 0 }
end
```

Avromatic throws an exception saying it can't find the schema file `test/__nested_nested_record_sub_record.avsc` on disk (I am using a schema_store).

I do see that the TypeFactory will always build an anonymous class for record types, unless I register a type using `config.register_type('test.__nested_nested_record_sub_record', SubRecord)`, so I'm guessing this is the correct way to go about getting what I need. What I need help with is building an Avromatic Model for that Subrecord. Any tips? 

Edit, I was able to get it working like this, more or less:
```ruby
Avromatic.configure do |config|
  config.eager_load_models = [
    "NestedNestedRecord"
  ]

  config.prepare!

  config.register_type('test.__nested_nested_record_sub_record', SubRecord)
end

class SubRecord < Avromatic.nested_models['test.__nested_nested_record_sub_record']
  include MyValidations
end
```
but this feels strange. Still wondering if this is the recommended way.

**Comment by jturkel** [comment]
Avromatic needs an `Avro::Schema` instance for every model it builds. Generally the easiest way to do this is to create a schema file on disk for each non-autogenerated Avromatic model (i.e. `test.nested_nested_record` and `test.__nested_nested_record_sub_record` in your example) so the schema store can lazily load Avro schemas as they're used. However, you can also configure a custom schema store via the `Avromatic.schema_store` setting to do more advanced registeration/lookup. For example, you could use the following schema store which makes all nested schemas available too (with the downside of not lazy loading schemas):

```ruby
class CustomSchemaStore
  attr_reader :schemas

  def initialize(path)
    @schemas = {}
    Dir["#{path}/**/*.avsc"].each do |file|
      schema = Avro::Schema.parse(IO.read(file))
      register_schema(schema)
    end
  end

  def find(name, namespace = nil)
    fullname = Avro::Name.make_fullname(name, namespace)
    schemas[fullname]
  end

  def register_schema(schema)
    if schema.is_a?(Avro::Schema::RecordSchema)
      return if schemas.include?(schema.fullname)
      
      schemas[schema.fullname] = schema
      schema.fields.each do |field|
        register_schema(field.type)
      end
    elsif schema.is_a?(Avro::Schema::ArraySchema)
      register_schema(schema.items)
    elsif schema.is_a?(Avro::Schema::MapSchema)
      register_schema(schema.values) 
    elsif schema.is_a?(Avro::Schema::UnionSchema)
      schema.schemas.each do |member_schema|
        register_schema(member_schema)
      end
    end
  end
end
```
Your Avromatic initializer would then be something like the following which interacts more safely with the Rails classloader:
```ruby
Avromatic.configure do |config|
  config.schema_store = CustomSchemaStore.new('my/avro/path')
  config.eager_load_models = [
    "SubRecord"
  ]
end
```
