### ISSUE TITLE
support models for nested schemas

### ISSUE THREAD

**Issue by tjwp** [salsify/avromatic#35]
Sometimes it is useful to be able to define a model for a schema that is embedded within another definition. 

For this purpose, we could walk a parsed Avro schema to find all the referenced schema. This would support something like the following to define a model for a nested/referenced schema:

``` ruby
Avromatic::Model.build(schema_name: 'com.example.outer_record', nested_schema_name: 'com.example.inner_record')
```

The model would be defined based on the fields for the `inner_record` schema.

**Comment by jturkel** [comment]
@tjwp - Do you think Avromatic's nested model support is sufficient to close this issue?

**Comment by jturkel** [comment]
@tjwp - Think this issue can be closed?

**Comment by tjwp** [comment]
Yes, I think this can be closed. I must have missed it when you raised the question previously.
