### ISSUE TITLE
value_attributes_for_avro doesn't behave as expected on 0.28.1

### ISSUE THREAD

**Issue by timothysu** [salsify/avromatic#77]
It appears that classes aren't preserved for some reason, I haven't had time to investigate:
```
- [{"__avromatic_encoding_provider"=>#<Core::Events::BooleanPropertyValueCollection property: #<Reference id: SalsifyUuid(s-00007360-0000-0000-0000-000000000000), type: "property", external_id: "boolean property">, value_data_type: "boolean", values: [true]>, "__avromatic_member_index"=>2}],
+ [{"__avromatic_encoding_provider"=>{"property"=>{"id"=>"s-00007360-0000-0000-0000-000000000000", "type"=>"property", "external_id"=>"boolean property"}, "value_data_type"=>"boolean", "values"=>[true]}, "__avromatic_member_index"=>2}],
```

https://circleci.com/gh/salsify/content-flow-service/1451

Seems to be related to 94b4904 and 18f6c69 because reverting to 0.27.0 fixes the issue @jkapell .

**Comment by jkapell** [comment]
There is behavior change in 0.28.1 such that value_attributes_for_avro no longer guarantees that the returned values will be fully serialized. In some cases, in particular when a model contains a reference to another immutable model, the latter will not be fully serialized but instead wrapped in a hash containing a single key "__avromatic_encoding_provider" that points to the model object. Serialization of these immutable model pointers is deferred to and handled by Avromatic::IO::DatumWriter during Avro encoding of the containing model.  This enables caching and reuse of the Avro encoded form of immutable models. It can be disabled by setting Avromatic.use_encoding_providers = false. That said, value_objects_for_avro arguably shouldn't be considered part of Avromatic's public interface and thus it would be better if your tests did not call it directly.

**Comment by tjwp** [comment]
I think it would make sense to add a method that is part of the public API that returns what `value_attributes_for_avro` used to before the various optimization embellishments. There were a couple of times where I almost added this, or thought of providing a friendlier alias for `value_attributes_for_avro`.

**Comment by jkapell** [comment]
Hey Tim! I support that idea. Would be easy enough to implement. Any suggestions on what to call it? to_h?

**Comment by tjwp** [comment]
`#avro_value_datum` and `#avro_key_datum` can now be used to get a hash of attributes without any customizations to improve encoding performance.
